109 fix dropdown
fga-eps-mds/2020-2-G4-Frontend pull request #24
Opened 2021-03-20 18:50 UTC by yukioz

issue: fga-eps-mds/2020-2-G4#109

## Descrição:
Consertamos o input de dropdown acrescentado "onChange" no componente e adicionamos um valor inicial já está pronto para uso.

2021-03-21 16:26 UTC, gabibguedes requested changes
Faltam algumas alterações

2021-03-21 16:26 UTC, gabibguedes commented on src/Pages/RegisterScreen/index.js
> +          <option>admin</option>
Essas opções que o usuário vê tem que estar em português

2021-03-21 16:26 UTC, gabibguedes commented on src/Pages/ClientRegisterScreen/index.js
> +  const [policeStationOption, setPoliceStationOption] = useState('DPSS');
Nessa tela de registro de clientes faltou alterar o genero das opções de cargo para algo mais neutro.

2021-03-21 16:26 UTC, gabibguedes commented on src/Pages/RegisterScreen/index.js
> +          style={{ boxSizing: 'border-box', borderRadius: '1.5vw', border: '2px solid #000000' }}
A seta do dropdown na lateral está muito colada a borda, tentem colocar uma margem maior

2021-03-21 16:44 UTC, yukioz commented on src/Pages/ClientRegisterScreen/index.js
> +  const [policeStationOption, setPoliceStationOption] = useState('DPSS');
Entendo, tem alguma sugestão para algo mais neutro?

2021-03-21 16:46 UTC, yukioz commented on src/Pages/RegisterScreen/index.js
> +          style={{ boxSizing: 'border-box', borderRadius: '1.5vw', border: '2px solid #000000' }}
Ok

2021-03-23 21:19 UTC, GabrielOak approved these changes
Muito bom!

2021-03-23 21:20 UTC, GabrielOak approved these changes
Ok!

2021-03-23 21:22 UTC, gabibguedes approved these changes

2021-03-23 21:22 UTC, merged