Arrumar Modal
fga-eps-mds/2020-2-G4-Frontend pull request #33
Opened 2021-03-25 05:29 UTC by Thiagof99

closes fga-eps-mds/2020-2-G4#122

## Descrição

Alteramos o componente da modal para utilizar o bootstrap e ficar responsivo.

2021-03-25 18:46 UTC, JPedroCh requested changes

2021-03-25 18:46 UTC, JPedroCh commented on src/Components/ModalComp/index.js
> +  };
É preciso limpar os states depois do submit para que a modal não esteja preenchida quando clicar no botão de nova categoria.

2021-03-25 21:17 UTC, DaviMarinho commented on src/Components/ModalComp/index.js
> +  };
Feito!

2021-03-25 21:52 UTC, JPedroCh approved these changes
ok

2021-03-26 04:07 UTC, GabrielOak commented
@Thiagof99 @DaviMarinho atualizem a branch

2021-03-26 23:02 UTC, EzequielDeOliveira approved these changes

2021-03-26 23:02 UTC, merged