Criação das telas de visualização e listagem de demandas
fga-eps-mds/2020-2-G4-Frontend pull request #39
Opened 2021-04-02 11:30 UTC by JPedroCh

## Descrição

Implementação de interface responsiva e funções para visualização e conclusão de demandas.

2021-04-02 18:55 UTC, vitorl-s approved these changes
Ok!

2021-04-02 21:14 UTC, DafneM requested changes

2021-04-02 21:14 UTC, DafneM commented on src/Pages/ListDemandsScreen/index.js
> +  useEffect(() => {
Quando tem 2 demandas, uma que não existe e uma que existe, a que não existe fica aparecendo e sumindo. Além disso, quando sobra só uma, o filtro não funciona.

2021-04-03 00:59 UTC, DaviMarinho commented on src/Pages/ListDemandsScreen/index.js
> +  useEffect(() => {
Feito!

2021-04-03 01:38 UTC, DafneM approved these changes
Ok

2021-04-03 01:40 UTC, merged