170 view disabled clients
fga-eps-mds/2020-2-G4-Frontend pull request #44
Opened 2021-04-06 23:16 UTC by yukioz

closes: #fga-eps-mds/2020-2-G4/issues/170

# Descrição:
Finalizado o filtro de clientes desativados e ativos. As alterações acompanham pequenas alterações no back-end.

2021-04-07 21:54 UTC, gabibguedes commented
Quando o cliente estiver desativado, deve ser possível ativa-lo novamente. Mudem o botão de desativar para ativar nesses casos

2021-04-09 00:25 UTC, GabrielOak requested changes

2021-04-09 00:25 UTC, GabrielOak commented on src/Components/ClientProfileData/index.js
> +      setText('Ativar');
Ícone da lixeira para ativar um cliente

2021-04-09 00:25 UTC, GabrielOak commented on src/Components/ClientProfileData/index.js
>                  <FaRegTrashAlt />
Botão de desativar deveria ser vermelho

2021-04-09 03:00 UTC, DaviMarinho commented on src/Components/ClientProfileData/index.js
>                  <FaRegTrashAlt />
Feito!

2021-04-09 03:00 UTC, DaviMarinho commented on src/Components/ClientProfileData/index.js
> +      setText('Ativar');
Feito!

2021-04-09 21:47 UTC, JPedroCh approved these changes
Ótimo trabalho!

2021-04-09 22:33 UTC, GabrielOak requested changes
- Deixar o ícone da lixeira vermelha assim como o texto.

2021-04-09 23:18 UTC, GabrielOak approved these changes
Muito bom!

2021-04-09 23:19 UTC, merged