FIX Sector ID sendo utilizado como nome na tela de visualizar demanda
fga-eps-mds/2020-2-G4-Frontend pull request #47
Opened 2021-04-08 21:12 UTC by JPedroCh

## Descrição 
Foi corrigido o erro da tela de visualizar demanda em que o sectorID estava sendo utilizado como nome do setor.

2021-04-08 23:53 UTC, DaviMarinho reviewed
Muito bom!

2021-04-08 23:53 UTC, DaviMarinho commented
Muito bom!

2021-04-09 01:27 UTC, gabibguedes requested changes
A atualização do histórico está com delay, ao encaminhar o setor ou adicionar uma atualização, a página não atualiza, ao fazer uma 2a alteração que a tela atualiza com as informações da 1a

2021-04-09 23:26 UTC, gabibguedes approved these changes
Ok

2021-04-09 23:39 UTC, DaviMarinho commented
Muito bom!

2021-04-09 23:41 UTC, DaviMarinho approved these changes
Muito bom!

2021-04-09 23:41 UTC, gabibguedes approved these changes
ok

2021-04-09 23:42 UTC, merged