157 update demand screen
fga-eps-mds/2020-2-G4-Frontend pull request #48
Opened 2021-04-09 08:00 UTC by yukioz

issue: #fga-eps-mds/2020-2-G4/issues/157
issue: #fga-eps-mds/2020-2-G4/issues/151

# Descrição:

Finalizado as telas de criar e editar demandas.

2021-04-11 19:29 UTC, JPedroCh requested changes

2021-04-11 19:29 UTC, JPedroCh commented on src/Pages/CreateDemandsScreen/index.js
>        {/* Começa aki */}
Remover comentários.

2021-04-11 19:29 UTC, JPedroCh commented on src/Utils/validations.js
> +
O campo de processo deve poder ficar vazio.

2021-04-11 19:29 UTC, JPedroCh commented on src/Components/SectorDropdown/index.js
> +  ];
As opções do dropdown do setor não estão pegando os setores da API.

2021-04-11 22:03 UTC, JPedroCh requested changes

2021-04-11 22:03 UTC, JPedroCh commented on src/Pages/UpdateDemandScreen/index.js
> +    }
Existem funções prontas que fazem o mesmo processo, utilizem.

2021-04-14 00:49 UTC, vitorl-s approved these changes
LGTM!

2021-04-14 00:50 UTC, yukioz commented on src/Pages/UpdateDemandScreen/index.js
> +    }
usei forEach como pedido.

2021-04-14 00:50 UTC, yukioz commented on src/Components/SectorDropdown/index.js
> +  ];
agora o dropdown pega da APi de setores

2021-04-14 00:50 UTC, yukioz commented on src/Utils/validations.js
> +
está vazio

2021-04-14 00:51 UTC, yukioz commented on src/Pages/CreateDemandsScreen/index.js
>        {/* Começa aki */}
removido

2021-04-14 00:57 UTC, JPedroCh approved these changes
LGTM!

2021-04-14 00:58 UTC, merged