38 navbar
fga-eps-mds/2020-2-G4-Frontend pull request #6
Opened 2021-02-27 21:03 UTC by JPedroCh

Issue: fga-eps-mds/2020-2-G4#38

## Descrição:
Criamos a barra de navegação.

2021-02-28 23:28 UTC, gabibguedes requested changes
Tá muito bom, só precisa de alguns ajustes

2021-02-28 23:28 UTC, gabibguedes commented on src/Components/NavbarComp/index.js
> +        <>
Esse <> e </> envolvendo o código da navbar é desnecessário. Em react, só pode retornar um componente, isso é usado quando é retornado mais de um componente, e o desenvolvedor não quis usar outra tag, como a div, para envolver os 2 ou mais componentes que está retornando. No caso de vocês já tem um componente que envolve todo o retorno, a <Navbar>.

2021-02-28 23:28 UTC, gabibguedes commented on src/Components/NavbarComp/index.js
> +        <Navbar fixed = 'top' style = {{backgroundColor: colors.primary}}>
Façam que nem nos outros componentes e utilizem um arquivo separado para estilo, ao invés de declara-lo no meio do código.

2021-02-28 23:32 UTC, gabibguedes commented
Outro detalhe que esqueci de comentar, achei o tamanho um pouco grande também, se puderem diminuir um pouco. Tipo colocar a fonte em 2vh e a altura da imagem em 5vh acho q fica melhor...

2021-03-01 21:55 UTC, JPedroCh commented on src/Components/NavbarComp/index.js
> +        <Navbar fixed = 'top' style = {{backgroundColor: colors.primary}}>
Foi corrigido.

2021-03-01 21:57 UTC, GabrielOak approved these changes

2021-03-01 21:58 UTC, merged